# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: clean the maven
      run: mvn clean install -DskipTests -pl jest-common -am

    - name: test run without NonDex
      run: mvn -pl jest-common test -Dtest=io.searchbox.indices.RolloverTest#testBasicUriGeneration

    - name: test run with NonDex
      run: mvn -pl jest-common edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=io.searchbox.indices.RolloverTest#testBasicUriGeneration
    
